language: node_js
node_js:
  - 12

services:
  - docker

  #Pre-testing installs
install:
  - echo "nothing needs to be installed"

#script to be run such as tests

before_script:
  - echo "no tests"

script:
  - docker --version #print docker version
  - docker build -t LordTravis .
  - docker tag LordTravis waqasnoor/LordTravis:latest

# Tasks to perform after image
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push waqasnoor/LordTravis
